In [2]:
import numpy as np
import pickle
import numpy.matlib
# didnt work ??? import functions.py.ipynb as f

In [20]:
# Loades an entire batch
def LoadBatch(filename):
	""" Copied from the dataset website """ 
	with open('Datasets/'+filename, 'rb') as fo:
		dict = pickle.load(fo, encoding='bytes') 
	return dict

def softmax(x):
    """ Standard definition of the softmax function """
    return np.exp(x) / np.sum(np.exp(x), axis=0)



def ReadData(filename):
    data_batch = LoadBatch(filename)
    
    # get pixel data
    pixel_data = data_batch[b'data']
    # labels for each image
    labels = data_batch[b'labels']
    # one-hot rep. of labels
    one_hot = np.eye(10)[labels]
    return pixel_data, one_hot, labels

def GetMeanAndStd(data):  
    print(data)
    # Kanske ändra
    mean = np.mean(data, 0)
    std = np.std(data, 0) # nånting saknas 
    return mean, std

# input trainings data mean std
def Normalize(train, validation, test, mean, std):
        # convert to floar
        train = np.float64(train)
        validation = np.float64(validation)
        test = np.float64(test)
        
        # Lurigt
        train -= mean 
        train /= std
    
        validation -= mean
        validation /= std
        
        test -= mean
        test /= std
        
        return train, validation, test
        
        #train = train    
def GetWeightAndBias(X, Y):
    W_size = np.shape(X)
    b_size = np.shape(Y)

    # loc = mean, scale = std
    W = np.random.normal(loc=0.0, scale=0.01, size=W_size)
    b = np.random.normal(loc=0.0, scale=0.01, size=b_size[0])
    
    return W, b

def EvaluateClassifier(X, W, b):
    print(X.shape)
    print(W.shape)
    print(b.shape)
    P = np.shape(X)
    W *= X
    W += b
    P = softmax(s)
    return P

In [21]:
# Read data
X_train, Y_train, y_test = ReadData('data_batch_1')
X_val_train, Y_val_train, y_val_test = ReadData('data_batch_2')
X_test_train, Y_test_train, y_test_test = ReadData('test_batch')

# Gets mean and std of training data
X_mean, X_std = GetMeanAndStd(X_train)

[[ 59  43  50 ... 140  84  72]
 [154 126 105 ... 139 142 144]
 [255 253 253 ...  83  83  84]
 ...
 [ 71  60  74 ...  68  69  68]
 [250 254 211 ... 215 255 254]
 [ 62  61  60 ... 130 130 131]]


In [22]:
# Normalize all data w.r.t. mean and std of training data
X_train_normalized, X_val_train_normalized, X_test_train_normalized = Normalize(X_train, X_val_train, X_test_train, X_mean, X_std)

In [23]:
# Create model params W and b
# W = Weight, b = bias
W, b = GetWeightAndBias(X_train_normalized, Y_train)

print(W)
print(b.size)
print(b)

[[ 2.51405608e-03 -9.30387699e-03 -9.79604602e-03 ... -3.63667128e-03
  -6.05096676e-03 -1.11976376e-02]
 [-1.54664004e-02 -4.03341544e-03 -2.96410761e-03 ... -4.54523792e-03
  -7.94548650e-03  3.23887876e-03]
 [-9.32536534e-04 -2.45234102e-03 -6.81513512e-03 ...  1.54116413e-02
  -1.95717750e-03 -3.48180863e-04]
 ...
 [-6.83818096e-03 -4.88631203e-03 -2.53255356e-02 ... -6.89556966e-03
   1.36262393e-03  6.13256852e-03]
 [ 1.18903512e-02  1.76239490e-02 -7.96005230e-05 ... -5.69642302e-03
  -1.05770263e-02  3.24540891e-03]
 [ 1.32733525e-02  2.02983616e-02 -2.82670911e-03 ...  1.21204061e-02
   4.05636805e-03  1.83974725e-02]]
10000
[ 0.00710517 -0.00956444  0.00750355 ...  0.0119481   0.00831068
 -0.0067609 ]


In [24]:
print(X_train_normalized[0])
P = EvaluateClassifier(X_train_normalized, W, b)
print(P)

[-0.99022072 -1.21342601 -1.13375625 ...  0.39523272 -0.45995317
 -0.64501523]
(10000, 3072)
(10000, 3072)
(10000,)


ValueError: operands could not be broadcast together with shapes (10000,3072) (10000,) (10000,3072) 